using Newtonsoft.Json.Linq;
// ReSharper disable InconsistentNaming
// ReSharper disable ClassNeverInstantiated.Local
// ReSharper disable UnusedAutoPropertyAccessor.Local

namespace EosDataScraper.Services
{

    public partial class DappComService
    {
        #region generated by http://json2csharp.com/

        //private class Chain
        //{
        //    public int pk { get; set; }
        //    public string name { get; set; }
        //    public string icon { get; set; }
        //    public string icon_new { get; set; }
        //    public string unit { get; set; }
        //    public string explorer { get; set; }
        //    public bool has_ranked { get; set; }
        //}

        private class Category
        {
            //public int pk { get; set; }
            public string name { get; set; }
            //public string icon { get; set; }
        }

        //private class Tag
        //{
        //    public string name { get; set; }
        //}

        //private class Social
        //{
        //    public string name { get; set; }
        //    public string url { get; set; }
        //}

        //private class Statistics
        //{
        //    public string balance { get; set; }
        //    public int dau { get; set; }
        //    public double trading_volume_24h { get; set; }
        //    public double trading_volume_7d { get; set; }
        //    public double ranking { get; set; }
        //}

        private class App
        {
            //public int pk { get; set; }
            public string identifier { get; set; }
            //public string name_en { get; set; }
            public string developer { get; set; }
            //public string icon { get; set; }
            //public List<object> images { get; set; }
            //public Chain chain { get; set; }
            public Category category { get; set; }
            public string @abstract { get; set; }
            public string desc_en { get; set; }
            //public List<Tag> tags { get; set; }
            //public string create_time { get; set; }
            public string url { get; set; }
            //public int state { get; set; }
            public JToken[] contracts { get; set; }
            //public List<Social> socials { get; set; }
            //public Statistics statistics { get; set; }
            //public int views { get; set; }
            //public int shares { get; set; }
            //public int likes { get; set; }
            //public int comments_count { get; set; }
            //public int score { get; set; }
            //public bool favorite { get; set; }
            //public bool is_like { get; set; }
        }

        //private class Chain2
        //{
        //    public int pk { get; set; }
        //    public string name { get; set; }
        //    public string icon { get; set; }
        //    public string icon_new { get; set; }
        //}

        //private class Category2
        //{
        //    public int pk { get; set; }
        //    public string name { get; set; }
        //    public string icon { get; set; }
        //}

        //private class Related
        //{
        //    public int pk { get; set; }
        //    public string identifier { get; set; }
        //    public string name_en { get; set; }
        //    public Chain2 chain { get; set; }
        //    public Category2 category { get; set; }
        //    public string icon { get; set; }
        //}

        //private class Dataset
        //{
        //    public List<int> data { get; set; }
        //}

        //private class Charts
        //{
        //    public List<string> labels { get; set; }
        //    public List<Dataset> datasets { get; set; }
        //}

        //private class User
        //{
        //    public int today { get; set; }
        //    public int weekly { get; set; }
        //    public int total { get; set; }
        //    public int best { get; set; }
        //    public Charts charts { get; set; }
        //}

        //private class Dataset2
        //{
        //    public List<double> data { get; set; }
        //}

        //private class Charts2
        //{
        //    public List<string> labels { get; set; }
        //    public List<Dataset2> datasets { get; set; }
        //}

        //private class Ranking
        //{
        //    public int today { get; set; }
        //    public int avg { get; set; }
        //    public int best { get; set; }
        //    public Charts2 charts { get; set; }
        //}

        //private class Dataset3
        //{
        //    public List<int> data { get; set; }
        //}

        //private class Charts3
        //{
        //    public List<string> labels { get; set; }
        //    public List<Dataset3> datasets { get; set; }
        //}

        //private class Amount
        //{
        //    public int today { get; set; }
        //    public int weekly { get; set; }
        //    public int total { get; set; }
        //    public int best { get; set; }
        //    public Charts3 charts { get; set; }
        //}

        //private class Dataset4
        //{
        //    public List<double> data { get; set; }
        //}

        //private class Charts4
        //{
        //    public List<string> labels { get; set; }
        //    public List<Dataset4> datasets { get; set; }
        //}

        //private class Volume
        //{
        //    public double today { get; set; }
        //    public double weekly { get; set; }
        //    public double total { get; set; }
        //    public double best { get; set; }
        //    public Charts4 charts { get; set; }
        //}

        //private class Community
        //{
        //    public int facebook { get; set; }
        //    public double facebook_gr { get; set; }
        //    public int twitter { get; set; }
        //    public double twitter_gr { get; set; }
        //    public int telegram { get; set; }
        //    public double telegram_gr { get; set; }
        //    public int discord { get; set; }
        //    public double discord_gr { get; set; }
        //    public int community { get; set; }
        //    public double community_gr { get; set; }
        //}

        //private class Stats
        //{
        //    public double balance { get; set; }
        //    public User user { get; set; }
        //    public Ranking ranking { get; set; }
        //    public Amount amount { get; set; }
        //    public Volume volume { get; set; }
        //    public Community community { get; set; }
        //}

        private class RootObject
        {
            public App app { get; set; }
            //public List<object> article { get; set; }
            //public List<object> comments { get; set; }
            //public List<Related> related { get; set; }
            //public Stats stats { get; set; }
        }

        #endregion
    }
}
