using System.Collections.Generic;
using Newtonsoft.Json;

namespace EosDataScraper.Services
{
    public partial class DappRadarService
    {
        #region generated by http://json2csharp.com/

        private class Info
        {
            [JsonProperty("id")]
            public int Id { get; set; }

            [JsonProperty("author")]
            public string Author { get; set; }

            [JsonProperty("title")]
            public string Title { get; set; }

            [JsonProperty("description")]
            public string Description { get; set; }

            [JsonProperty("url")]
            public string Url { get; set; }

            [JsonProperty("category")]
            public string Category { get; set; }

            [JsonProperty("slug")]
            public string Slug { get; set; }
        }

        private class Contract
        {
            [JsonProperty("title")]
            public string Title { get; set; }

            [JsonProperty("address")]
            public string Address { get; set; }

            public override string ToString()
            {
                return $"{Address} | {Title}";
            }
        }

        private class Data
        {
            [JsonProperty("info")]
            public Info Info { get; set; }

            [JsonProperty("contracts")]
            public List<Contract> Contracts { get; set; }
        }

        private class RootObject
        {
            [JsonProperty("data")]
            public Data Data { get; set; }
        }

        #endregion
    }
}
