-- Table: public.api_user
-- DROP TABLE public.api_user;
CREATE TABLE public.api_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    login character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password bytea NOT NULL,
    role integer NOT NULL,

    CONSTRAINT api_user_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.api_user 
    OWNER to eos_data_light_user;